### ISSUE TITLE
GitHub Rate Limiting

### ISSUE THREAD

**Issue by olivernyc** [nycmeshnet/nycmesh-configgen#1]
Unauthenticated GitHub requests are limited to 60 per hour. It's pretty easy to hit this limit so we should either add a GitHub login or figure out another way to fetch the templates.

**Comment by zgiles** [comment]
Interesting, Shoot.. ok. good to know.
Is there any ill effect from hitting the limit besides being limited; or, will it open eventually ( so we dont have to fix this _today_ )

**Comment by olivernyc** [comment]
Yeah not super urgent, just have to wait a few minutes for the rate limiting to cool down. Let's reopen this if it become an issue.
