### ISSUE TITLE
add filter to conf. to allow clock to synch via SNTP to OmniTik 

### ISSUE THREAD

**Issue by OlivierMorf** [nycmeshnet/nycmesh-configgen#5]
Need to add a line in Firewall Omni Script for clock synchronisation via SNTP request. 

I have been adding manually the "filter" to the firewall manually (via CLI) to allow the clock to synch. via SNTP so Omni log shows events with proper timestamps which help a lot when debugging.

/ip firewall filter add chain=input connection-state=related,established place-before=2

**Comment by zgiles** [comment]
This was done recently in nycmeshnet/nycmesh-configs
